const noRequestData = [{ offset: "—", type: "—", description: "请求 Data 为空，Byte Count = 0。" }];

const identityResponse = [
  { offset: "0", type: "UINT8", description: "Expansion Code，通常为 0xFE。" },
  { offset: "1–2", type: "UINT8 × 2", description: "地址用制造商码与设备类型码。" },
  { offset: "3", type: "UINT8", description: "主站后续请求应使用的最少前导码数量。" },
  { offset: "4–8", type: "位域 / UINT8", description: "HART、设备、软件、硬件修订，物理信号类型与设备标志。" },
  { offset: "9–11", type: "UINT24 BE", description: "Device ID；与设备类型共同组成后续长地址。" },
  { offset: "12+", type: "修订相关", description: "响应前导码、最后设备变量码、配置变更计数、扩展状态、扩展制造商与设备 Profile 等。" },
];

const tagDescriptorDate = [
  { offset: "0–5", type: "Packed ASCII", description: "8 字符短 Tag。" },
  { offset: "6–17", type: "Packed ASCII", description: "16 字符 Descriptor。" },
  { offset: "18–20", type: "日期", description: "日、月、年减 1900，各 1 byte。" },
];

const definition = (command, label, options) => ({
  command,
  label,
  category: command <= 22 || [38, 48].includes(command) ? "Universal" : "Common Practice",
  address: command === 0 ? "short" : [11, 21].includes(command) ? "discovery" : "long",
  requestLength: 0,
  requestExample: "",
  requestFields: noRequestData,
  responseLength: "变长",
  responseFields: [],
  verify: "先检查 RC 与 DS，再按设备修订解释 Data。",
  ...options,
});

export const HART_COMMAND_FRAMES = [
  definition(0, "读取唯一标识", {
    responseLength: "12–22+",
    responseFields: identityResponse,
    verify: "RC = 0 后才接受身份；用设备报告的前导码和 Device ID 建立后续长地址。",
  }),
  definition(11, "按短 Tag 读取唯一标识", {
    requestLength: 6,
    requestExample: "50 11 F0 C3 0C 31",
    requestFields: [{ offset: "0–5", type: "Packed ASCII", description: "8 字符短 Tag；4 个字符压缩为 3 bytes。" }],
    responseLength: "12–22+",
    responseFields: identityResponse,
    verify: "先确认返回身份对应目标 Tag，再转为长地址通信。",
  }),
  definition(20, "读取 Long Tag", {
    responseLength: 32,
    responseFields: [{ offset: "0–31", type: "Latin-1", description: "32 字节 Long Tag，移除尾随空格或 NUL。" }],
    verify: "按 Latin-1 解码，不要按 Packed ASCII 解码。",
  }),
  definition(21, "按 Long Tag 读取唯一标识", {
    requestLength: 32,
    requestExample: "48 41 52 54 2D 44 45 56 49 43 45 2D 30 30 31 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20",
    requestFields: [{ offset: "0–31", type: "Latin-1", description: "32 字节 Long Tag；不足部分补空格或按设备约定补 NUL。" }],
    responseLength: "12–22+",
    responseFields: identityResponse,
    verify: "RC = 0 后仍要核对返回的制造商、设备类型和 Device ID。",
  }),
  definition(22, "写入 Long Tag", {
    requestLength: 32,
    requestExample: "48 41 52 54 2D 44 45 56 49 43 45 2D 30 30 31 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20",
    requestFields: [{ offset: "0–31", type: "Latin-1", description: "新的 32 字节 Long Tag。" }],
    responseLength: 32,
    responseFields: [{ offset: "0–31", type: "Latin-1", description: "设备接受的 Long Tag，通常回显最终值。" }],
    verify: "写成功后重新发送 Cmd 20，不以本次回显代替独立回读。",
  }),
  definition(1, "读取 PV", {
    responseLength: 5,
    responseFields: [
      { offset: "0", type: "Unit Code", description: "PV 工程单位码。" },
      { offset: "1–4", type: "FLOAT32 BE", description: "PV 数值，IEEE 754 大端。" },
    ],
    verify: "结合 Unit Code、DS 和量程判断数值；NaN 不能直接当作 0。",
  }),
  definition(2, "读取回路电流与百分比", {
    responseLength: 8,
    responseFields: [
      { offset: "0–3", type: "FLOAT32 BE", description: "回路电流，单位 mA。" },
      { offset: "4–7", type: "FLOAT32 BE", description: "量程百分比，单位 %。" },
    ],
    verify: "将数字电流与实测回路电流交叉核对，并检查模拟输出固定/饱和状态。",
  }),
  definition(3, "读取动态变量与电流", {
    responseLength: 24,
    responseFields: [
      { offset: "0–3", type: "FLOAT32 BE", description: "回路电流，mA。" },
      { offset: "4 / 5–8", type: "Unit + FLOAT32", description: "PV 单位码与数值。" },
      { offset: "9 / 10–13", type: "Unit + FLOAT32", description: "SV 单位码与数值。" },
      { offset: "14 / 15–18", type: "Unit + FLOAT32", description: "TV 单位码与数值。" },
      { offset: "19 / 20–23", type: "Unit + FLOAT32", description: "QV 单位码与数值。" },
    ],
    verify: "先用 Cmd 50 确认 PV/SV/TV/QV 映射；未使用槽位可能返回 HART NaN。",
  }),
  definition(8, "读取动态变量分类", {
    responseLength: 4,
    responseFields: [
      { offset: "0", type: "Classification", description: "PV 分类码。" },
      { offset: "1", type: "Classification", description: "SV 分类码。" },
      { offset: "2", type: "Classification", description: "TV 分类码。" },
      { offset: "3", type: "Classification", description: "QV 分类码。" },
    ],
    verify: "分类码 0 表示尚未分类；不要仅凭槽位名称猜测测量语义。",
  }),
  definition(9, "按编号读取设备变量及状态", {
    requestLength: "1–8",
    requestExample: "F6 F7 F8 F9",
    requestFields: [{ offset: "0–7", type: "DV Code 列表", description: "请求 1–8 个 Device Variable Code；示例 F6–F9 为 PV–QV。" }],
    responseLength: "5 + 8 × N",
    responseFields: [
      { offset: "0", type: "位域", description: "Extended Device Status。" },
      { offset: "1 + 8n", type: "UINT8", description: "第 n 个 Device Variable Code。" },
      { offset: "2 + 8n", type: "Classification", description: "变量分类码。" },
      { offset: "3 + 8n", type: "Unit Code", description: "工程单位码。" },
      { offset: "4–7 + 8n", type: "FLOAT32 BE", description: "变量值。" },
      { offset: "8 + 8n", type: "位域", description: "变量状态与限值状态。" },
      { offset: "末 4 bytes", type: "UINT32 BE", description: "时间戳，1/32000 秒单位。" },
    ],
    verify: "逐槽校验返回的 DV Code，不能假定响应顺序永远与请求完全一致。",
  }),
  definition(6, "写轮询地址 / 回路电流模式", {
    requestLength: 2,
    requestExample: "00 01",
    requestFields: [
      { offset: "0", type: "UINT8", description: "Polling Address，按目标修订限制范围。" },
      { offset: "1", type: "枚举", description: "Loop Current Mode：0 禁用，1 启用。" },
    ],
    responseLength: 2,
    responseFields: [
      { offset: "0", type: "UINT8", description: "设备接受的 Polling Address。" },
      { offset: "1", type: "枚举", description: "设备接受的 Loop Current Mode。" },
    ],
    verify: "地址改变后旧地址可能立即失效；用新地址发送 Cmd 7 与 Cmd 0 验证。",
  }),
  definition(7, "读取回路配置", {
    responseLength: 2,
    responseFields: [
      { offset: "0", type: "UINT8", description: "Polling Address。" },
      { offset: "1", type: "枚举", description: "Loop Current Mode。" },
    ],
    verify: "与 Cmd 6 的结果和设备状态保持一致。",
  }),
  definition(12, "读取设备 Message", {
    responseLength: 24,
    responseFields: [{ offset: "0–23", type: "Packed ASCII", description: "32 字符 Message。" }],
    verify: "每 3 bytes 解出 4 字符，并移除尾随空格。",
  }),
  definition(13, "读取 Tag / Descriptor / Date", {
    responseLength: 21,
    responseFields: tagDescriptorDate,
    verify: "日期的年份字节需要加 1900；不要把压缩文本当 Latin-1。",
  }),
  definition(14, "读取传感器信息", {
    responseLength: "16+",
    responseFields: [
      { offset: "0–2", type: "UINT24 BE", description: "Transducer Serial Number。" },
      { offset: "3", type: "Unit Code", description: "传感器量程单位码。" },
      { offset: "4–7", type: "FLOAT32 BE", description: "Upper Sensor Limit。" },
      { offset: "8–11", type: "FLOAT32 BE", description: "Lower Sensor Limit。" },
      { offset: "12–15", type: "FLOAT32 BE", description: "Minimum Span。" },
      { offset: "16+", type: "修订相关", description: "扩展字段按设备修订解析。" },
    ],
    verify: "传感器极限不是当前 LRV/URV；量程配置应再读取 Cmd 15。",
  }),
  definition(15, "读取输出信息", {
    responseLength: "15+",
    responseFields: [
      { offset: "0", type: "枚举", description: "Alarm Selection Code。" },
      { offset: "1", type: "枚举", description: "Transfer Function Code。" },
      { offset: "2", type: "Unit Code", description: "PV 量程单位码。" },
      { offset: "3–6", type: "FLOAT32 BE", description: "Upper Range Value。" },
      { offset: "7–10", type: "FLOAT32 BE", description: "Lower Range Value。" },
      { offset: "11–14", type: "FLOAT32 BE", description: "Damping，单位秒。" },
      { offset: "15+", type: "修订相关", description: "写保护、私有标签或模拟通道标志等扩展字段。" },
    ],
    verify: "修改量程或阻尼后独立回读本命令，并核对 Cmd 2 / 3。",
  }),
  definition(16, "读取最终装配号", {
    responseLength: 3,
    responseFields: [{ offset: "0–2", type: "UINT24 BE", description: "Final Assembly Number。" }],
    verify: "该字段用于追溯，不等于 Device ID。",
  }),
  definition(19, "写入最终装配号", {
    requestLength: 3,
    requestExample: "00 00 01",
    requestFields: [{ offset: "0–2", type: "UINT24 BE", description: "新的 Final Assembly Number。" }],
    responseLength: 3,
    responseFields: [{ offset: "0–2", type: "UINT24 BE", description: "设备接受的最终装配号。" }],
    verify: "写后用 Cmd 16 独立回读。",
  }),
  definition(17, "写入设备 Message", {
    requestLength: 24,
    requestExample: "34 12 4E 50 53 81 38 31 60 34 54 D3 04 71 60 82 08 20 82 08 20 82 08 20",
    requestFields: [{ offset: "0–23", type: "Packed ASCII", description: "32 字符 Message。" }],
    responseLength: 24,
    responseFields: [{ offset: "0–23", type: "Packed ASCII", description: "设备接受的 Message。" }],
    verify: "写后用 Cmd 12 回读。",
  }),
  definition(18, "写入 Tag / Descriptor / Date", {
    requestLength: 21,
    requestExample: "50 11 F0 C3 0C 31 10 54 C3 48 94 14 24 F3 A0 82 08 20 08 01 7E",
    requestFields: tagDescriptorDate,
    responseLength: 21,
    responseFields: tagDescriptorDate,
    verify: "检查无效日期响应码；写后用 Cmd 13 回读。",
  }),
  definition(38, "复位 Configuration Changed 标志", {
    requestLength: "0 / 2",
    requestExample: "00 01",
    requestFields: [{ offset: "0–1", type: "UINT16 BE · 可选", description: "HART 7 配置变更计数；旧修订或特定流程可能为空。" }],
    responseLength: 2,
    responseFields: [{ offset: "0–1", type: "UINT16 BE", description: "设备当前 Configuration Change Counter。" }],
    verify: "计数不匹配时不要重试覆盖；先重新读取配置并更新主站缓存。",
  }),
  definition(48, "读取附加设备状态", {
    responseLength: "1–N",
    responseFields: [
      { offset: "0–5", type: "位域", description: "设备特定附加状态；语义由 EDD / FDI 或厂商文档给出。" },
      { offset: "6", type: "位域", description: "Extended Device Status（字段存在时）。" },
      { offset: "7", type: "枚举", description: "Device Operating Mode（字段存在时）。" },
      { offset: "8–13", type: "位域", description: "标准化状态与模拟通道固定/饱和映射，随修订扩展。" },
    ],
    verify: "以 Byte Count 限定边界；不要读取不存在的可选字节，也不要只展示原始 HEX。",
  }),
  definition(33, "读取最多四个设备变量", {
    requestLength: "1–4",
    requestExample: "F6 F7 F8 F9",
    requestFields: [{ offset: "0–3", type: "DV Code 列表", description: "请求 1–4 个 Device Variable Code。" }],
    responseLength: "6 × N",
    responseFields: [
      { offset: "6n", type: "UINT8", description: "第 n 个 Device Variable Code。" },
      { offset: "6n + 1", type: "Unit Code", description: "工程单位码。" },
      { offset: "6n + 2…5", type: "FLOAT32 BE", description: "变量值。" },
    ],
    verify: "逐组核对返回的 DV Code；不支持变量可能返回 HART NaN。",
  }),
  definition(50, "读取动态变量分配", {
    responseLength: 4,
    responseFields: [
      { offset: "0", type: "DV Code", description: "PV 映射。" },
      { offset: "1", type: "DV Code", description: "SV 映射。" },
      { offset: "2", type: "DV Code", description: "TV 映射。" },
      { offset: "3", type: "DV Code", description: "QV 映射。" },
    ],
    verify: "映射结果用于解释 Cmd 3；不要默认 PV 永远等于 DV0。",
  }),
  definition(51, "写入动态变量分配", {
    requestLength: 4,
    requestExample: "00 01 02 03",
    requestFields: [
      { offset: "0", type: "DV Code", description: "新的 PV 映射。" },
      { offset: "1", type: "DV Code", description: "新的 SV 映射。" },
      { offset: "2", type: "DV Code", description: "新的 TV 映射。" },
      { offset: "3", type: "DV Code", description: "新的 QV 映射。" },
    ],
    responseLength: 4,
    responseFields: [
      { offset: "0–3", type: "DV Code × 4", description: "设备最终接受的 PV / SV / TV / QV 映射。" },
    ],
    verify: "写后用 Cmd 50，再用 Cmd 3 核对数值与单位。",
  }),
  definition(54, "读取设备变量信息", {
    requestLength: 1,
    requestExample: "00",
    requestFields: [{ offset: "0", type: "DV Code", description: "目标 Device Variable Code。" }],
    responseLength: "修订相关",
    responseFields: [
      { offset: "0", type: "DV Code", description: "返回的 Device Variable Code。" },
      { offset: "1+", type: "复合结构", description: "传感器序列号、单位、上下限、最小量程、分类、Family、更新周期与属性等；字段集合随 Common Practice 修订扩展。" },
    ],
    verify: "先按 Byte Count 和设备修订选择布局；完整字段必须以目标版本 HCF_SPEC-151 与 EDD / FDI 为准。",
  }),
  definition(34, "写入 PV 阻尼值", {
    requestLength: 4,
    requestExample: "3F 80 00 00",
    requestFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "阻尼时间，单位秒；示例为 1.0 s。" }],
    responseLength: 4,
    responseFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "设备最终采用的阻尼值。" }],
    verify: "写后用 Cmd 15 回读，警告 RC = 8 时以返回的实际值为准。",
  }),
  definition(35, "写入 PV 量程值", {
    requestLength: 9,
    requestExample: "07 42 C8 00 00 00 00 00 00",
    requestFields: [
      { offset: "0", type: "Unit Code", description: "PV 量程单位码；示例仅演示字节位置。" },
      { offset: "1–4", type: "FLOAT32 BE", description: "Upper Range Value；示例为 100.0。" },
      { offset: "5–8", type: "FLOAT32 BE", description: "Lower Range Value；示例为 0.0。" },
    ],
    responseLength: 9,
    responseFields: [
      { offset: "0", type: "Unit Code", description: "设备接受的量程单位码。" },
      { offset: "1–4", type: "FLOAT32 BE", description: "设备接受的 URV。" },
      { offset: "5–8", type: "FLOAT32 BE", description: "设备接受的 LRV。" },
    ],
    verify: "先确认 Unit Code 与 DCS 缩放；写后用 Cmd 15、2、3 分别核对配置和输出。",
  }),
  definition(44, "写入 PV 工程单位", {
    requestLength: 1,
    requestExample: "07",
    requestFields: [{ offset: "0", type: "Unit Code", description: "目标 PV 工程单位码。" }],
    responseLength: 1,
    responseFields: [{ offset: "0", type: "Unit Code", description: "设备最终采用的单位码。" }],
    verify: "写后用 Cmd 1 与 Cmd 15 核对单位、数值和量程是否同步换算。",
  }),
  definition(53, "写入设备变量单位", {
    requestLength: 2,
    requestExample: "00 07",
    requestFields: [
      { offset: "0", type: "DV Code", description: "目标 Device Variable Code。" },
      { offset: "1", type: "Unit Code", description: "目标工程单位码。" },
    ],
    responseLength: 2,
    responseFields: [{ offset: "0–1", type: "DV Code + Unit", description: "设备接受的变量码与单位码。" }],
    verify: "写后用 Cmd 54 与 Cmd 9 独立回读。",
  }),
  definition(55, "写入设备变量阻尼值", {
    requestLength: 5,
    requestExample: "00 3F 80 00 00",
    requestFields: [
      { offset: "0", type: "DV Code", description: "目标 Device Variable Code。" },
      { offset: "1–4", type: "FLOAT32 BE", description: "阻尼时间，单位秒；示例为 1.0 s。" },
    ],
    responseLength: 5,
    responseFields: [{ offset: "0–4", type: "DV Code + FLOAT32", description: "设备接受的变量码与阻尼值。" }],
    verify: "写后用 Cmd 54 回读；不要把 DV 阻尼和 PV 阻尼混为一谈。",
  }),
  definition(40, "进入 / 退出固定电流模式", {
    requestLength: 4,
    requestExample: "40 80 00 00",
    requestFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "目标固定电流，mA；示例为 4.0 mA，退出值按目标规格与设备实现。" }],
    responseLength: 4,
    responseFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "设备实际采用的固定电流值。" }],
    verify: "检查 DS 的 Analog Output Fixed 位；结束时退出固定模式并用 Cmd 2 验证恢复。",
  }),
  definition(45, "修整回路电流零点", {
    requestLength: 4,
    requestExample: "40 80 00 00",
    requestFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "外部参考表实测的低点电流，mA；示例为 4.0。" }],
    responseLength: 4,
    responseFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "设备接受的低点参考电流。" }],
    verify: "先用 Cmd 40 固定低点；修整后重新实测，而不是只看数字回显。",
  }),
  definition(46, "修整回路电流增益", {
    requestLength: 4,
    requestExample: "41 A0 00 00",
    requestFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "外部参考表实测的高点电流，mA；示例为 20.0。" }],
    responseLength: 4,
    responseFields: [{ offset: "0–3", type: "FLOAT32 BE", description: "设备接受的高点参考电流。" }],
    verify: "完成零点后再做增益；退出固定模式并复测 4/12/20 mA。",
  }),
  definition(52, "设置设备变量零点", {
    requestLength: 1,
    requestExample: "00",
    requestFields: [{ offset: "0", type: "DV Code", description: "要在当前基准条件下置零的 Device Variable Code。" }],
    responseLength: 1,
    responseFields: [{ offset: "0", type: "DV Code", description: "设备接受并执行置零的变量码。" }],
    verify: "确认工况稳定和变量选择正确；用 Cmd 9 读取该变量并检查状态。",
  }),
];
